version: "3"

services:
  spark-master:
    image: sparkaio/first:v0
    container_name: spark-master
    hostname: sparkmaster
    ports:
      - "8080:8080"
      - "7077:7077"

  spark-worker:
    image: sparkaio/first:v0
    depends_on:
      - spark-master
    command: sh -c "${SPARK_HOME}/sbin/start-slave.sh spark://sparkmaster:7077 && tail -f /dev/null"